### PR TITLE
fix extensions folder + fix cpu/memory requests

### PR DESCRIPTION
**Pull request by guimou**
Fixes for #8, #11

### CODE REVIEW

**Comment by nnachefski** [comment]
How do i get these changes to come through the KfDef deployment via ODH Operator?  I just deployed a test instance and do not see the changes yet.

**Comment by nnachefski** [comment]
ah, i see.  I think the nifi manifest has to be updated.

https://github.com/guimou/odh-manifests/tree/master/nifi

```
  repos:
    - name: kf-manifests
      uri: 'https://github.com/opendatahub-io/manifests/tarball/v1.3-openshift'
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v1.1.1'
    - name: manifests-guimou
      uri: 'https://github.com/guimou/odh-manifests/tarball/dev'
```

**Comment by guimou** [comment]
Oh!!! I totally forgot that I had those manifests here. You're right, I will have to update them.
Although I would maybe remove them as anyway it won't fit in the new ODH architecture where we are removing many things like that.

**Comment by shalberd** [comment]
Maybe a repository like for Airflow on opendatahub-io-contrib would be the way to go forward?

https://github.com/orgs/opendatahub-io-contrib/repositories

still kustomize-based, just in a repo in that location ...

Nice work on this, I got Nifi running and usable this way on Openshift 4.10.20. For some fiddling-around with NOAA weather data pooling into a weather topic of a Kafka cluster, provided with the Strimzi operator.

**Comment by guimou** [comment]
Yes, that's one of the repo I have to move there (after Spark and Custom notebooks).

**Pull request merged**
